[package]
name = "zuzunza_zetenc"
description = "ZetEnc decryption compatible with wscp-library/zetenc (Go)"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[dependencies]
aes = "0.8.4"
cfb-mode = "0.8.2"
sha2 = "0.10.8"
thiserror = { workspace = true }
